# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='squad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='squads.Squad'),
            preserve_default=False,
        ),
    ]
