# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0004_player_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='Striker', max_length=20),
            preserve_default=False,
        ),
    ]
